[server]
# IP address to bind to - Default: "127.0.0.1"
listen_ip = "127.0.0.1"
# Port to bind to - Default: 3333
listen_port = 3333
# Server's user-facing URL (mandatory, CHANGE THIS)
public_url = "http://127.0.0.1:3333"
# Whitelist of client origins to allow - Default: (none (unrestricted))
#allowed_origins = [] 


[headers]
# Static resources cache max-age we indicate to clients - Default: 604800 (1 week)
static_ttl = 604800
# Discovery JSON cache max-age we indicate to clients - Default: 604800 (1 week)
discovery_ttl = 604800
# Keys JSON cache max-age we indicate to clients - Default: 86400 (1 day)
keys_ttl = 86400


[crypto]
# Duration that id_tokens are valid for - Default: 600 (10 minutes)
token_ttl = 600
# Array of file paths to PEM-formatted signing keys - (mandatory, CHANGE THIS)
keyfiles = [ "/home/cole/code/dex-portier-demo/portier-key.pem"]
# Text of the key file in PEM format (set either this or keyfiles) - Default: (none)
#keytext =


[redis]
# Redis connection URL - Default: (mandatory, CHANGE THIS) (example: redis://localhost, redis://localhost:6379/0)
url = "redis://localhost"
# Time that users have to complete authentication - Default: 900 (15 minutes)
session_ttl = 900
# Time that provider discovery documents are cached - Default: 3600 (1 hour)
cache_ttl = 3600


[smtp]
# Display name for confirmation emails - Default: "Portier"
from_name = "Portier"
# Sender address for confirmation emails - (mandatory, CHANGE THIS)
from_address = "portier@localhost"
# Outgoing mailserver address - (mandatory, CHANGE THIS)
server = "127.0.0.1:1025"
# Outgoing mailserver username - Default: (none)
username = "none"
# Outgoing mailserver password - Default: (none)
password = "none"


[limit]
# Authentication ratelimit for a single email address - Default: "5/min"
# Currently only supports "/min" unit.
per_email = "5/min"


#[providers."gmail.com"]
# Google OAuth API Client ID - Default: (none)
#client_id =
# Google OpenID Connect discovery URL - Default: "https://accounts.google.com/.well-known/openid-configuration"
#discovery_url = "https://accounts.google.com/.well-known/openid-configuration"
# Google OpenID Connect id_token issuer domain - Default: "accounts.google.com"
#issuer_domain = "accounts.google.com"
